[workspace]
resolver = "2"
members = [
    "crates/slate-domain",
    "crates/slate-brain",
    "crates/slate-comfy",
    "crates/slate-engine",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.3.2"
# Original Slate copyright: Sam Wasserman (see NOTICE). Maintainer of this fork (Agent-Slate): thcabq352.
authors = ["Sam Wasserman", "thcabq352"]
repository = "https://github.com/thcabq352/Agent-Slate"
homepage = "https://github.com/thcabq352/Agent-Slate"
documentation = "https://github.com/thcabq352/Agent-Slate#readme"
